services:
    grachev.core_bundle.type.enum:
        class: Grachev\CoreBundle\Form\EnumType
        tags:
            - { name: form.type }

    grachev.core_bundle.event_listener.enum_subscriber:
        class: Grachev\CoreBundle\EventListener\EnumSubscriber
        arguments: [ "@config_cache_factory", "%kernel.cache_dir%" ]
        tags:
            - { name: doctrine.event_subscriber, connection: default }